spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customerdb
    password: hbcustomer_password
    username: hbcustomer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'